# ✨ Numpy ✨

## Why Numpy array not a list?

In [1]:
import numpy as np
import time
import random


# ⚔️ Basics of ndarrays
### 🗡️ Creat 100 x 3 random list and a 100 x 3 random array

In [2]:
## Python list
plist = [[random.random() for j in range(3)] for i in range(10)]
## np array
arr = np.random.rand(10,3)

### 🗡️ Print the number of rows and columns of the list and array

In [3]:
# dimentions
print(f"({len(plist)},{len(plist[0])})")
arr.shape

(10,3)


(10, 3)

### 🗡️ Print the second element from the first row

In [4]:
# access Values 
print(plist[0][1])
print(arr[0, 1])

0.4518428397304428
0.547231627142127


### 🗡️ Print a matrix that contains the elements from second row to 4th ans 2nd column to 3ed column
![Sliceing](\numpy-indexing-and-slicing.jpg)

In [5]:
# Slicing
print([x[1:3] for x in plist[1:5]])
print(arr[1:5,1:3])

[[0.7968703878233424, 0.4963619528498664], [0.6635550093080095, 0.5159220328281674], [0.9255254524268463, 0.9258563770077891], [0.7318250384513652, 0.7358698013251214]]
[[0.52609041 0.12966749]
 [0.73488655 0.53058432]
 [0.72841285 0.06798106]
 [0.60512969 0.45270789]]


## 🗡️ Shape and type

In [6]:
arr.shape

(10, 3)

In [7]:
arr.size

30

In [8]:
arr.dtype

dtype('float64')

In [9]:
arr.T

array([[0.22529025, 0.76341828, 0.59182767, 0.09022042, 0.6965922 ,
        0.16804957, 0.74420313, 0.5246785 , 0.09645607, 0.03224715],
       [0.54723163, 0.52609041, 0.73488655, 0.72841285, 0.60512969,
        0.61022555, 0.52280711, 0.49989951, 0.66645244, 0.10675395],
       [0.26375464, 0.12966749, 0.53058432, 0.06798106, 0.45270789,
        0.65969659, 0.71403898, 0.57191689, 0.03036395, 0.24525863]])

In [10]:
arr.flatten()

array([0.22529025, 0.54723163, 0.26375464, 0.76341828, 0.52609041,
       0.12966749, 0.59182767, 0.73488655, 0.53058432, 0.09022042,
       0.72841285, 0.06798106, 0.6965922 , 0.60512969, 0.45270789,
       0.16804957, 0.61022555, 0.65969659, 0.74420313, 0.52280711,
       0.71403898, 0.5246785 , 0.49989951, 0.57191689, 0.09645607,
       0.66645244, 0.03036395, 0.03224715, 0.10675395, 0.24525863])

# 📊 Aggregation Function

### 📊 Print the sum, min, max, and the mean  of all elements

In [11]:
# List
print("Python List")
print(f"Sum: {sum(sum(plist,[]))}")
print(f"Min: {min(map(min, plist))}")
print(f"Max: {max(map(max, plist))}")
print(f"Mean: {sum(sum(plist,[]))/(len(plist)*len(plist[0]))}")

print('\nnp Array')
# np Array
print(f"Sum: {arr.sum()}")
print(f"Min: {arr.min()}")
print(f"Max: {arr.max()}")
print(f"Mean: {arr.mean()}")

Python List
Sum: 14.838145037208486
Min: 0.05009022035036248
Max: 0.9830584077451715
Mean: 0.4946048345736162

np Array
Sum: 13.14684339325273
Min: 0.030363952675630745
Max: 0.7634182807347264
Mean: 0.43822811310842436


### 📊 Print the sum, min, max, and the mean  of each column

In [12]:
total = [0]* len(plist)
for row in plist:
    total = [total[j] +row[j] for j in range(len(row))]
total

[3.963196069609124, 5.3846350553804605, 5.490313912218902]

In [13]:
print("Python List")
print(f"Sum: {total}")


print('\nnp Array')
# np Array
print(f"Sum: {arr.sum(axis=0)}")
print(f"Min: {np.min(arr, axis=0)}")
print(f"Max: {arr.max(axis=0)}")
print(f"Mean: {arr.mean(axis=0)}")

Python List
Sum: [3.963196069609124, 5.3846350553804605, 5.490313912218902]

np Array
Sum: [3.93298326 5.54788969 3.66597045]
Min: [0.03224715 0.10675395 0.03036395]
Max: [0.76341828 0.73488655 0.71403898]
Mean: [0.39329833 0.55478897 0.36659704]


# 🚀 Universal Functions (Broadcasting)

In [14]:
np.add(2, arr)

array([[2.22529025, 2.54723163, 2.26375464],
       [2.76341828, 2.52609041, 2.12966749],
       [2.59182767, 2.73488655, 2.53058432],
       [2.09022042, 2.72841285, 2.06798106],
       [2.6965922 , 2.60512969, 2.45270789],
       [2.16804957, 2.61022555, 2.65969659],
       [2.74420313, 2.52280711, 2.71403898],
       [2.5246785 , 2.49989951, 2.57191689],
       [2.09645607, 2.66645244, 2.03036395],
       [2.03224715, 2.10675395, 2.24525863]])

In [15]:
np.log2(arr)

array([[-2.1501432 , -0.86977648, -1.92273162],
       [-0.38945436, -0.92661733, -2.94711131],
       [-0.75675093, -0.44440655, -0.91434605],
       [-3.47040218, -0.45717172, -3.87872334],
       [-0.52161377, -0.72468372, -1.14334763],
       [-2.57304123, -0.7125855 , -0.60012544],
       [-0.42623164, -0.93564933, -0.48592527],
       [-0.93049441, -1.00028998, -0.80612258],
       [-3.3739842 , -0.58542618, -5.04149658],
       [-4.95468439, -3.22763868, -2.02762417]])

In [16]:
1+arr

array([[1.22529025, 1.54723163, 1.26375464],
       [1.76341828, 1.52609041, 1.12966749],
       [1.59182767, 1.73488655, 1.53058432],
       [1.09022042, 1.72841285, 1.06798106],
       [1.6965922 , 1.60512969, 1.45270789],
       [1.16804957, 1.61022555, 1.65969659],
       [1.74420313, 1.52280711, 1.71403898],
       [1.5246785 , 1.49989951, 1.57191689],
       [1.09645607, 1.66645244, 1.03036395],
       [1.03224715, 1.10675395, 1.24525863]])

In [17]:
arr+ np.array([1, 2, 3])

array([[1.22529025, 2.54723163, 3.26375464],
       [1.76341828, 2.52609041, 3.12966749],
       [1.59182767, 2.73488655, 3.53058432],
       [1.09022042, 2.72841285, 3.06798106],
       [1.6965922 , 2.60512969, 3.45270789],
       [1.16804957, 2.61022555, 3.65969659],
       [1.74420313, 2.52280711, 3.71403898],
       [1.5246785 , 2.49989951, 3.57191689],
       [1.09645607, 2.66645244, 3.03036395],
       [1.03224715, 2.10675395, 3.24525863]])

In [18]:
arr+ [1, 2, 3]

array([[1.22529025, 2.54723163, 3.26375464],
       [1.76341828, 2.52609041, 3.12966749],
       [1.59182767, 2.73488655, 3.53058432],
       [1.09022042, 2.72841285, 3.06798106],
       [1.6965922 , 2.60512969, 3.45270789],
       [1.16804957, 2.61022555, 3.65969659],
       [1.74420313, 2.52280711, 3.71403898],
       [1.5246785 , 2.49989951, 3.57191689],
       [1.09645607, 2.66645244, 3.03036395],
       [1.03224715, 2.10675395, 3.24525863]])

# 🔬 Filtering and Masking

In [19]:
arr<0.5

array([[ True, False,  True],
       [False, False,  True],
       [False, False, False],
       [ True, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False, False, False],
       [False,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [20]:
arr[arr<0.5]

array([0.22529025, 0.26375464, 0.12966749, 0.09022042, 0.06798106,
       0.45270789, 0.16804957, 0.49989951, 0.09645607, 0.03036395,
       0.03224715, 0.10675395, 0.24525863])

# 🗂️ Sort
## Sort array In-Place

In [21]:
arr.sort()

In [22]:
arr

array([[0.22529025, 0.26375464, 0.54723163],
       [0.12966749, 0.52609041, 0.76341828],
       [0.53058432, 0.59182767, 0.73488655],
       [0.06798106, 0.09022042, 0.72841285],
       [0.45270789, 0.60512969, 0.6965922 ],
       [0.16804957, 0.61022555, 0.65969659],
       [0.52280711, 0.71403898, 0.74420313],
       [0.49989951, 0.5246785 , 0.57191689],
       [0.03036395, 0.09645607, 0.66645244],
       [0.03224715, 0.10675395, 0.24525863]])

In [27]:
arr = np.random.rand(10,3)

## Sort Array Along Different Axes
This method creates a sorted copy of the given NumPy array. 
It is mostly used in a multi-dimensional array when you want to sort along a given dimension.

In [28]:
np.sort(arr)

array([[0.16832974, 0.18218961, 0.83568002],
       [0.09742383, 0.79457651, 0.9069162 ],
       [0.13515999, 0.14671285, 0.65411649],
       [0.21333942, 0.4558722 , 0.73483061],
       [0.32216283, 0.4241069 , 0.90526765],
       [0.40463864, 0.62480872, 0.8371592 ],
       [0.01681858, 0.23590547, 0.52843456],
       [0.32085056, 0.65318897, 0.72902875],
       [0.53062665, 0.77979561, 0.9161536 ],
       [0.01214687, 0.08548534, 0.57218456]])

In [29]:
arr2 = np.arange(30).reshape((10, 3))
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

## Indirect sort 


In [30]:
# Returns the indices that would sort an array
ind = np.argsort(arr)
ind

array([[2, 1, 0],
       [0, 1, 2],
       [2, 1, 0],
       [0, 2, 1],
       [2, 0, 1],
       [1, 2, 0],
       [0, 2, 1],
       [0, 1, 2],
       [2, 0, 1],
       [1, 0, 2]], dtype=int64)

In [32]:
ind[-1]

array([1, 0, 2], dtype=int64)

In [101]:
arr2[ind]

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [6, 7, 8],
        [3, 4, 5]],

       [[3, 4, 5],
        [0, 1, 2],
        [6, 7, 8]],

       [[6, 7, 8],
        [3, 4, 5],
        [0, 1, 2]],

       [[0, 1, 2],
        [6, 7, 8],
        [3, 4, 5]],

       [[0, 1, 2],
        [6, 7, 8],
        [3, 4, 5]],

       [[3, 4, 5],
        [0, 1, 2],
        [6, 7, 8]],

       [[6, 7, 8],
        [0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [6, 7, 8],
        [3, 4, 5]],

       [[3, 4, 5],
        [0, 1, 2],
        [6, 7, 8]],

       [[3, 4, 5],
        [6, 7, 8],
        [0, 1, 2]],

       [[0, 1, 2],
        [6, 7, 8],
        [3, 4, 5]],

       [[3, 4, 5],
        [0, 1, 2],
        [6, 7, 8]],

       [[6, 7, 8],
        [0, 1, 2],
        [3, 4, 5]],

       [[6, 7, 8],
        [0, 1, 2],
        [3, 4, 5]]

# 🧮 Matrix multiplication

In [49]:
A = np.array([[1, 2],
             [3, 4]])
B = np.array([[3, 2],
             [1, 4]])


In [34]:
np.matmul(A, B)

array([[ 5, 10],
       [13, 22]])

In [35]:
np.matmul(B, A)

array([[ 9, 14],
       [13, 18]])

In [36]:
np.dot(A, B)

array([[ 5, 10],
       [13, 22]])

In [37]:
np.cross(A, B)

array([-4,  8])

In [38]:
np.cross(B, A)

array([ 4, -8])

## Inverse of a matrix

In [57]:
from numpy.linalg import inv, det
np.matmul(inv(A), A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [58]:
inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [59]:
A = np.array([[-1, 1, -1],
             [5, 2, -5],
             [6, -5, 1],
             [-5, 6, 0]])
B = np.array([[6, 5],
             [5, -6],
             [6, 0]])
np.matmul(A, B)

array([[ -7, -11],
       [ 10,  13],
       [ 17,  60],
       [  0, -61]])

In [60]:
B.T

array([[ 6,  5,  6],
       [ 5, -6,  0]])

In [61]:
C = np.array([[1, 0],
             [1, 3]])

In [54]:
inv(C)

array([[ 1.        ,  0.        ],
       [-0.33333333,  0.33333333]])

In [62]:
det(C)

3.0000000000000004

In [63]:
np.dot([1, 2, 3], [3, 6, 7]) 

36

In [64]:
np.matmul([1, 2, 3], [3, 6, 7])

36