# ✨ Numpy ✨

## Why Numpy array not a list?

In [1]:
import numpy as np
import time
import random


# ⚔️ Basics of ndarrays
### 🗡️ Creat 100 x 3 random list and a 100 x 3 random array

In [11]:
list_1 = [[random.random() for col in range(3)] for row in range(100)]
arr = np.random.rand(100, 3)
arr

array([[0.43351312, 0.62690421, 0.67665849],
       [0.62811245, 0.49165502, 0.7120639 ],
       [0.80966302, 0.07168449, 0.43495399],
       [0.12663422, 0.28357056, 0.06925394],
       [0.19777669, 0.90480428, 0.23543491],
       [0.91683512, 0.35625615, 0.24903985],
       [0.24744857, 0.98773283, 0.3087837 ],
       [0.71141086, 0.88426063, 0.6891158 ],
       [0.28345807, 0.44016351, 0.25488949],
       [0.56263912, 0.99116688, 0.26654394],
       [0.5630656 , 0.97070946, 0.43501334],
       [0.56859346, 0.31697914, 0.2675302 ],
       [0.30382445, 0.4922935 , 0.25157585],
       [0.43196335, 0.59356483, 0.66941821],
       [0.92228772, 0.3292863 , 0.62374205],
       [0.74332516, 0.41860367, 0.86673156],
       [0.86125019, 0.83097245, 0.58115084],
       [0.37282167, 0.82706454, 0.33839414],
       [0.70741008, 0.62769504, 0.3784828 ],
       [0.5288312 , 0.10066311, 0.3504682 ],
       [0.29881005, 0.25926034, 0.80573461],
       [0.39991444, 0.87159198, 0.75719259],
       [0.

### 🗡️ Print the number of rows and columns of the list and array

In [13]:
len(list_1), len(list_1[0])


(100, 3)

In [14]:
arr.shape

(100, 3)

### 🗡️ Print the second element from the first row

In [15]:
list_1[0][1]

0.600208339505119

In [17]:
arr[0, 1]

0.6269042086515906

### 🗡️ Print a matrix that contains the elements from second row to 4th ans 2nd column to 3ed column
![Sliceing](\numpy-indexing-and-slicing.jpg)

In [23]:
# Slicing
for row in list_1[1:4]:
    print(row[1:])


[0.5779384778666807, 0.19680125011412608]
[0.6817696910964227, 0.8313115925159423]
[0.26516416546271704, 0.5326338479399334]


In [24]:
arr[1:4, 1:]

array([[0.49165502, 0.7120639 ],
       [0.07168449, 0.43495399],
       [0.28357056, 0.06925394]])

## 🗡️ Shape and type

In [25]:
arr.size

300

In [26]:
arr.dtype

dtype('float64')

In [29]:
arr.flatten()

array([0.43351312, 0.62690421, 0.67665849, 0.62811245, 0.49165502,
       0.7120639 , 0.80966302, 0.07168449, 0.43495399, 0.12663422,
       0.28357056, 0.06925394, 0.19777669, 0.90480428, 0.23543491,
       0.91683512, 0.35625615, 0.24903985, 0.24744857, 0.98773283,
       0.3087837 , 0.71141086, 0.88426063, 0.6891158 , 0.28345807,
       0.44016351, 0.25488949, 0.56263912, 0.99116688, 0.26654394,
       0.5630656 , 0.97070946, 0.43501334, 0.56859346, 0.31697914,
       0.2675302 , 0.30382445, 0.4922935 , 0.25157585, 0.43196335,
       0.59356483, 0.66941821, 0.92228772, 0.3292863 , 0.62374205,
       0.74332516, 0.41860367, 0.86673156, 0.86125019, 0.83097245,
       0.58115084, 0.37282167, 0.82706454, 0.33839414, 0.70741008,
       0.62769504, 0.3784828 , 0.5288312 , 0.10066311, 0.3504682 ,
       0.29881005, 0.25926034, 0.80573461, 0.39991444, 0.87159198,
       0.75719259, 0.18632473, 0.5261512 , 0.77298283, 0.01018879,
       0.27645237, 0.0902222 , 0.4165744 , 0.40113478, 0.35944

In [30]:
arr.reshape(10, 30)

array([[0.43351312, 0.62690421, 0.67665849, 0.62811245, 0.49165502,
        0.7120639 , 0.80966302, 0.07168449, 0.43495399, 0.12663422,
        0.28357056, 0.06925394, 0.19777669, 0.90480428, 0.23543491,
        0.91683512, 0.35625615, 0.24903985, 0.24744857, 0.98773283,
        0.3087837 , 0.71141086, 0.88426063, 0.6891158 , 0.28345807,
        0.44016351, 0.25488949, 0.56263912, 0.99116688, 0.26654394],
       [0.5630656 , 0.97070946, 0.43501334, 0.56859346, 0.31697914,
        0.2675302 , 0.30382445, 0.4922935 , 0.25157585, 0.43196335,
        0.59356483, 0.66941821, 0.92228772, 0.3292863 , 0.62374205,
        0.74332516, 0.41860367, 0.86673156, 0.86125019, 0.83097245,
        0.58115084, 0.37282167, 0.82706454, 0.33839414, 0.70741008,
        0.62769504, 0.3784828 , 0.5288312 , 0.10066311, 0.3504682 ],
       [0.29881005, 0.25926034, 0.80573461, 0.39991444, 0.87159198,
        0.75719259, 0.18632473, 0.5261512 , 0.77298283, 0.01018879,
        0.27645237, 0.0902222 , 0.4165744 , 0.

# 📊 Aggregation Function

### 📊 Print the sum, min, max, and the mean  of all elements

In [32]:
np.sum(arr)

151.00537177221184

In [35]:
arr.mean()

0.5033512392407061

In [37]:
sum(map(sum , list_1))

139.71339514067446

### 📊 Print the sum, min, max, and the mean  of each column

In [40]:
np.sum(arr, axis= 0)

array([48.22658909, 55.08407193, 47.69471076])

# 🚀 Universal Functions (Broadcasting)

In [45]:
arr+[1, 2, 3]

array([[1.43351312, 2.62690421, 3.67665849],
       [1.62811245, 2.49165502, 3.7120639 ],
       [1.80966302, 2.07168449, 3.43495399],
       [1.12663422, 2.28357056, 3.06925394],
       [1.19777669, 2.90480428, 3.23543491],
       [1.91683512, 2.35625615, 3.24903985],
       [1.24744857, 2.98773283, 3.3087837 ],
       [1.71141086, 2.88426063, 3.6891158 ],
       [1.28345807, 2.44016351, 3.25488949],
       [1.56263912, 2.99116688, 3.26654394],
       [1.5630656 , 2.97070946, 3.43501334],
       [1.56859346, 2.31697914, 3.2675302 ],
       [1.30382445, 2.4922935 , 3.25157585],
       [1.43196335, 2.59356483, 3.66941821],
       [1.92228772, 2.3292863 , 3.62374205],
       [1.74332516, 2.41860367, 3.86673156],
       [1.86125019, 2.83097245, 3.58115084],
       [1.37282167, 2.82706454, 3.33839414],
       [1.70741008, 2.62769504, 3.3784828 ],
       [1.5288312 , 2.10066311, 3.3504682 ],
       [1.29881005, 2.25926034, 3.80573461],
       [1.39991444, 2.87159198, 3.75719259],
       [1.

In [49]:
np.log2(arr)

array([[-1.20585243, -0.67368308, -0.56350021],
       [-0.67090523, -1.02428172, -0.48992138],
       [-0.3046065 , -3.80219512, -1.20106528],
       [-2.98126079, -1.81822033, -3.85195999],
       [-2.3380557 , -0.14432234, -2.08659982],
       [-0.12526579, -1.48901319, -2.00555149],
       [-2.0147994 , -0.01780724, -1.69533149],
       [-0.4912451 , -0.17745644, -0.53718167],
       [-1.81879277, -1.18388854, -1.97205623],
       [-0.82971822, -0.01280012, -1.90755469],
       [-0.82862509, -0.04288854, -1.20086844],
       [-0.81453058, -1.65754018, -1.90222635],
       [-1.71869013, -1.02240941, -1.99093468],
       [-1.21101917, -0.75252249, -0.5790203 ],
       [-0.11671121, -1.60258561, -0.68097857],
       [-0.42793466, -1.25634312, -0.20634286],
       [-0.2154957 , -0.26712745, -0.78301542],
       [-1.42344237, -0.27392818, -1.56322349],
       [-0.49938131, -0.67186429, -1.40170034],
       [-0.9191208 , -3.31239297, -1.51264453],
       [-1.7426994 , -1.94752659, -0.311

# 🔬 Filtering and Masking

In [51]:
arr[arr<0.5]

array([0.43351312, 0.49165502, 0.07168449, 0.43495399, 0.12663422,
       0.28357056, 0.06925394, 0.19777669, 0.23543491, 0.35625615,
       0.24903985, 0.24744857, 0.3087837 , 0.28345807, 0.44016351,
       0.25488949, 0.26654394, 0.43501334, 0.31697914, 0.2675302 ,
       0.30382445, 0.4922935 , 0.25157585, 0.43196335, 0.3292863 ,
       0.41860367, 0.37282167, 0.33839414, 0.3784828 , 0.10066311,
       0.3504682 , 0.29881005, 0.25926034, 0.39991444, 0.18632473,
       0.01018879, 0.27645237, 0.0902222 , 0.4165744 , 0.40113478,
       0.35944807, 0.37454137, 0.1860404 , 0.18423862, 0.26490923,
       0.32121722, 0.2383736 , 0.36012536, 0.09475539, 0.09956631,
       0.04471899, 0.24359843, 0.18912642, 0.01813478, 0.11698545,
       0.34139506, 0.36996182, 0.40141335, 0.2273359 , 0.20074035,
       0.17106434, 0.03540832, 0.47624518, 0.01822273, 0.13791646,
       0.05939585, 0.32267058, 0.2456866 , 0.20494548, 0.12493806,
       0.01060955, 0.19271942, 0.48212101, 0.10604206, 0.27364

# 🗂️ Sort
## Sort array In-Place

In [53]:
arr.sort()

In [62]:
arr= np.random.rand(10, 3)


In [63]:
np.random.shuffle(arr)
arr

array([[0.76049139, 0.65365246, 0.26864121],
       [0.34266975, 0.84924937, 0.25124386],
       [0.62005702, 0.7153709 , 0.83351898],
       [0.27876532, 0.17659048, 0.19948952],
       [0.74991091, 0.96019462, 0.25985687],
       [0.27386035, 0.05661379, 0.50144729],
       [0.38347973, 0.73049197, 0.62524309],
       [0.76890193, 0.78999503, 0.7304119 ],
       [0.63328441, 0.20659131, 0.98596311],
       [0.65094213, 0.84109066, 0.72356802]])

## Sort Array Along Different Axes
This method creates a sorted copy of the given NumPy array. 
It is mostly used in a multi-dimensional array when you want to sort along a given dimension.

In [64]:
np.sort(arr)

array([[0.26864121, 0.65365246, 0.76049139],
       [0.25124386, 0.34266975, 0.84924937],
       [0.62005702, 0.7153709 , 0.83351898],
       [0.17659048, 0.19948952, 0.27876532],
       [0.25985687, 0.74991091, 0.96019462],
       [0.05661379, 0.27386035, 0.50144729],
       [0.38347973, 0.62524309, 0.73049197],
       [0.7304119 , 0.76890193, 0.78999503],
       [0.20659131, 0.63328441, 0.98596311],
       [0.65094213, 0.72356802, 0.84109066]])

In [65]:
arr

array([[0.76049139, 0.65365246, 0.26864121],
       [0.34266975, 0.84924937, 0.25124386],
       [0.62005702, 0.7153709 , 0.83351898],
       [0.27876532, 0.17659048, 0.19948952],
       [0.74991091, 0.96019462, 0.25985687],
       [0.27386035, 0.05661379, 0.50144729],
       [0.38347973, 0.73049197, 0.62524309],
       [0.76890193, 0.78999503, 0.7304119 ],
       [0.63328441, 0.20659131, 0.98596311],
       [0.65094213, 0.84109066, 0.72356802]])

## Indirect sort 


In [66]:
# Returns the indices that would sort an array
np.argsort(arr)

array([[2, 1, 0],
       [2, 0, 1],
       [0, 1, 2],
       [1, 2, 0],
       [2, 0, 1],
       [1, 0, 2],
       [0, 2, 1],
       [2, 0, 1],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)

# 🧮 Matrix multiplication

In [67]:
A = np.array([[1, 2],
             [3, 4]])
B = np.array([[3, 2],
             [1, 4]])


In [68]:
np.matmul(A, B)

array([[ 5, 10],
       [13, 22]])

In [69]:
np.matmul(B, A)

array([[ 9, 14],
       [13, 18]])

In [70]:
np.dot(A, B)

array([[ 5, 10],
       [13, 22]])

In [71]:
np.cross(A, B)

array([-4,  8])

In [72]:
np.cross(B, A)

array([ 4, -8])