In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


In [3]:
df = pd.read_csv(r"../../dataset/laptopData.csv")

In [4]:
df

Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3   
1            1.0   Apple           Ultrabook   13.3   
2            2.0      HP            Notebook   15.6   
3            3.0   Apple           Ultrabook   15.4   
4            4.0   Apple           Ultrabook   13.3   
...          ...     ...                 ...    ...   
1298      1298.0  Lenovo  2 in 1 Convertible     14   
1299      1299.0  Lenovo  2 in 1 Convertible   13.3   
1300      1300.0  Lenovo            Notebook     14   
1301      1301.0      HP            Notebook   15.6   
1302      1302.0    Asus            Notebook   15.6   

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600   
1                                       1440x900   
2                              Full HD 1920x1080   
3             IPS Panel Retina Display 2880x1800   
4             IPS Panel Retina Display 2560x1600   
...                                          ...   
1298   IPS Panel Full HD / Touchscreen 1920x1080   
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300                                    1366x768   
1301                                    1366x768   
1302                                    1366x768   

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD   
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3                     Intel Core i7 2.7GHz  16GB            512GB SSD   
4                     Intel Core i5 3.1GHz   8GB            256GB SSD   
...                                    ...   ...                  ...   
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD   

                               Gpu       OpSys  Weight        Price  
0     Intel Iris Plus Graphics 640       macOS  1.37kg   71378.6832  
1           Intel HD Graphics 6000       macOS  1.34kg   47895.5232  
2            Intel HD Graphics 620       No OS  1.86kg   30636.0000  
3               AMD Radeon Pro 455       macOS  1.83kg  135195.3360  
4     Intel Iris Plus Graphics 650       macOS  1.37kg   96095.8080  
...                            ...         ...     ...          ...  
1298         Intel HD Graphics 520  Windows 10   1.8kg   33992.6400  
1299         Intel HD Graphics 520  Windows 10   1.3kg   79866.7200  
1300             Intel HD Graphics  Windows 10   1.5kg   12201.1200  
1301            AMD Radeon R5 M330  Windows 10  2.19kg   40705.9200  
1302             Intel HD Graphics  Windows 10   2.2kg   19660.3200  

[1303 rows x 12 columns]

In [5]:
df.isnull().sum()

Unnamed: 0          30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [6]:
df = df.fillna(method = 'bfill')
df

C:\Users\71519\AppData\Local\Temp\ipykernel_20780\659356365.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method = 'bfill')


Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3   
1            1.0   Apple           Ultrabook   13.3   
2            2.0      HP            Notebook   15.6   
3            3.0   Apple           Ultrabook   15.4   
4            4.0   Apple           Ultrabook   13.3   
...          ...     ...                 ...    ...   
1298      1298.0  Lenovo  2 in 1 Convertible     14   
1299      1299.0  Lenovo  2 in 1 Convertible   13.3   
1300      1300.0  Lenovo            Notebook     14   
1301      1301.0      HP            Notebook   15.6   
1302      1302.0    Asus            Notebook   15.6   

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600   
1                                       1440x900   
2                              Full HD 1920x1080   
3             IPS Panel Retina Display 2880x1800   
4             IPS Panel Retina Display 2560x1600   
...                                          ...   
1298   IPS Panel Full HD / Touchscreen 1920x1080   
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300                                    1366x768   
1301                                    1366x768   
1302                                    1366x768   

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD   
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3                     Intel Core i7 2.7GHz  16GB            512GB SSD   
4                     Intel Core i5 3.1GHz   8GB            256GB SSD   
...                                    ...   ...                  ...   
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD   

                               Gpu       OpSys  Weight        Price  
0     Intel Iris Plus Graphics 640       macOS  1.37kg   71378.6832  
1           Intel HD Graphics 6000       macOS  1.34kg   47895.5232  
2            Intel HD Graphics 620       No OS  1.86kg   30636.0000  
3               AMD Radeon Pro 455       macOS  1.83kg  135195.3360  
4     Intel Iris Plus Graphics 650       macOS  1.37kg   96095.8080  
...                            ...         ...     ...          ...  
1298         Intel HD Graphics 520  Windows 10   1.8kg   33992.6400  
1299         Intel HD Graphics 520  Windows 10   1.3kg   79866.7200  
1300             Intel HD Graphics  Windows 10   1.5kg   12201.1200  
1301            AMD Radeon R5 M330  Windows 10  2.19kg   40705.9200  
1302             Intel HD Graphics  Windows 10   2.2kg   19660.3200  

[1303 rows x 12 columns]

In [7]:
df.isnull().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [8]:
df1 = df.copy()
df1['Ram'] = df1['Ram'].str.replace("GB", "")
df1

Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3   
1            1.0   Apple           Ultrabook   13.3   
2            2.0      HP            Notebook   15.6   
3            3.0   Apple           Ultrabook   15.4   
4            4.0   Apple           Ultrabook   13.3   
...          ...     ...                 ...    ...   
1298      1298.0  Lenovo  2 in 1 Convertible     14   
1299      1299.0  Lenovo  2 in 1 Convertible   13.3   
1300      1300.0  Lenovo            Notebook     14   
1301      1301.0      HP            Notebook   15.6   
1302      1302.0    Asus            Notebook   15.6   

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600   
1                                       1440x900   
2                              Full HD 1920x1080   
3             IPS Panel Retina Display 2880x1800   
4             IPS Panel Retina Display 2560x1600   
...                                          ...   
1298   IPS Panel Full HD / Touchscreen 1920x1080   
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300                                    1366x768   
1301                                    1366x768   
1302                                    1366x768   

                                       Cpu Ram               Memory  \
0                     Intel Core i5 2.3GHz   8            128GB SSD   
1                     Intel Core i5 1.8GHz   8  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8            256GB SSD   
3                     Intel Core i7 2.7GHz  16            512GB SSD   
4                     Intel Core i5 3.1GHz   8            256GB SSD   
...                                    ...  ..                  ...   
1298            Intel Core i7 6500U 2.5GHz   4            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4            500GB HDD   

                               Gpu       OpSys  Weight        Price  
0     Intel Iris Plus Graphics 640       macOS  1.37kg   71378.6832  
1           Intel HD Graphics 6000       macOS  1.34kg   47895.5232  
2            Intel HD Graphics 620       No OS  1.86kg   30636.0000  
3               AMD Radeon Pro 455       macOS  1.83kg  135195.3360  
4     Intel Iris Plus Graphics 650       macOS  1.37kg   96095.8080  
...                            ...         ...     ...          ...  
1298         Intel HD Graphics 520  Windows 10   1.8kg   33992.6400  
1299         Intel HD Graphics 520  Windows 10   1.3kg   79866.7200  
1300             Intel HD Graphics  Windows 10   1.5kg   12201.1200  
1301            AMD Radeon R5 M330  Windows 10  2.19kg   40705.9200  
1302             Intel HD Graphics  Windows 10   2.2kg   19660.3200  

[1303 rows x 12 columns]

In [9]:
df1['Weight'] = df1['Weight'].str.replace("kg", "")
df1

Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3   
1            1.0   Apple           Ultrabook   13.3   
2            2.0      HP            Notebook   15.6   
3            3.0   Apple           Ultrabook   15.4   
4            4.0   Apple           Ultrabook   13.3   
...          ...     ...                 ...    ...   
1298      1298.0  Lenovo  2 in 1 Convertible     14   
1299      1299.0  Lenovo  2 in 1 Convertible   13.3   
1300      1300.0  Lenovo            Notebook     14   
1301      1301.0      HP            Notebook   15.6   
1302      1302.0    Asus            Notebook   15.6   

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600   
1                                       1440x900   
2                              Full HD 1920x1080   
3             IPS Panel Retina Display 2880x1800   
4             IPS Panel Retina Display 2560x1600   
...                                          ...   
1298   IPS Panel Full HD / Touchscreen 1920x1080   
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300                                    1366x768   
1301                                    1366x768   
1302                                    1366x768   

                                       Cpu Ram               Memory  \
0                     Intel Core i5 2.3GHz   8            128GB SSD   
1                     Intel Core i5 1.8GHz   8  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8            256GB SSD   
3                     Intel Core i7 2.7GHz  16            512GB SSD   
4                     Intel Core i5 3.1GHz   8            256GB SSD   
...                                    ...  ..                  ...   
1298            Intel Core i7 6500U 2.5GHz   4            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4            500GB HDD   

                               Gpu       OpSys Weight        Price  
0     Intel Iris Plus Graphics 640       macOS   1.37   71378.6832  
1           Intel HD Graphics 6000       macOS   1.34   47895.5232  
2            Intel HD Graphics 620       No OS   1.86   30636.0000  
3               AMD Radeon Pro 455       macOS   1.83  135195.3360  
4     Intel Iris Plus Graphics 650       macOS   1.37   96095.8080  
...                            ...         ...    ...          ...  
1298         Intel HD Graphics 520  Windows 10    1.8   33992.6400  
1299         Intel HD Graphics 520  Windows 10    1.3   79866.7200  
1300             Intel HD Graphics  Windows 10    1.5   12201.1200  
1301            AMD Radeon R5 M330  Windows 10   2.19   40705.9200  
1302             Intel HD Graphics  Windows 10    2.2   19660.3200  

[1303 rows x 12 columns]

In [10]:
def split_memory_column(df1, column_name):
    # Split the column into two new columns
    df1[['Memory', 'Type']] = df1[column_name].str.split(' ', n=1, expand=True)
    return df1

In [11]:
df1 = split_memory_column(df1, 'Memory')
df1

Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3   
1            1.0   Apple           Ultrabook   13.3   
2            2.0      HP            Notebook   15.6   
3            3.0   Apple           Ultrabook   15.4   
4            4.0   Apple           Ultrabook   13.3   
...          ...     ...                 ...    ...   
1298      1298.0  Lenovo  2 in 1 Convertible     14   
1299      1299.0  Lenovo  2 in 1 Convertible   13.3   
1300      1300.0  Lenovo            Notebook     14   
1301      1301.0      HP            Notebook   15.6   
1302      1302.0    Asus            Notebook   15.6   

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600   
1                                       1440x900   
2                              Full HD 1920x1080   
3             IPS Panel Retina Display 2880x1800   
4             IPS Panel Retina Display 2560x1600   
...                                          ...   
1298   IPS Panel Full HD / Touchscreen 1920x1080   
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300                                    1366x768   
1301                                    1366x768   
1302                                    1366x768   

                                       Cpu Ram Memory  \
0                     Intel Core i5 2.3GHz   8  128GB   
1                     Intel Core i5 1.8GHz   8  128GB   
2               Intel Core i5 7200U 2.5GHz   8  256GB   
3                     Intel Core i7 2.7GHz  16  512GB   
4                     Intel Core i5 3.1GHz   8  256GB   
...                                    ...  ..    ...   
1298            Intel Core i7 6500U 2.5GHz   4  128GB   
1299            Intel Core i7 6500U 2.5GHz  16  512GB   
1300  Intel Celeron Dual Core N3050 1.6GHz   2   64GB   
1301            Intel Core i7 6500U 2.5GHz   6    1TB   
1302  Intel Celeron Dual Core N3050 1.6GHz   4  500GB   

                               Gpu       OpSys Weight        Price  \
0     Intel Iris Plus Graphics 640       macOS   1.37   71378.6832   
1           Intel HD Graphics 6000       macOS   1.34   47895.5232   
2            Intel HD Graphics 620       No OS   1.86   30636.0000   
3               AMD Radeon Pro 455       macOS   1.83  135195.3360   
4     Intel Iris Plus Graphics 650       macOS   1.37   96095.8080   
...                            ...         ...    ...          ...   
1298         Intel HD Graphics 520  Windows 10    1.8   33992.6400   
1299         Intel HD Graphics 520  Windows 10    1.3   79866.7200   
1300             Intel HD Graphics  Windows 10    1.5   12201.1200   
1301            AMD Radeon R5 M330  Windows 10   2.19   40705.9200   
1302             Intel HD Graphics  Windows 10    2.2   19660.3200   

               Type  
0               SSD  
1     Flash Storage  
2               SSD  
3               SSD  
4               SSD  
...             ...  
1298            SSD  
1299            SSD  
1300  Flash Storage  
1301            HDD  
1302            HDD  

[1303 rows x 13 columns]

In [12]:
df1['Memory'] = df1['Memory'].str.replace("GB", "")
df1

Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3   
1            1.0   Apple           Ultrabook   13.3   
2            2.0      HP            Notebook   15.6   
3            3.0   Apple           Ultrabook   15.4   
4            4.0   Apple           Ultrabook   13.3   
...          ...     ...                 ...    ...   
1298      1298.0  Lenovo  2 in 1 Convertible     14   
1299      1299.0  Lenovo  2 in 1 Convertible   13.3   
1300      1300.0  Lenovo            Notebook     14   
1301      1301.0      HP            Notebook   15.6   
1302      1302.0    Asus            Notebook   15.6   

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600   
1                                       1440x900   
2                              Full HD 1920x1080   
3             IPS Panel Retina Display 2880x1800   
4             IPS Panel Retina Display 2560x1600   
...                                          ...   
1298   IPS Panel Full HD / Touchscreen 1920x1080   
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300                                    1366x768   
1301                                    1366x768   
1302                                    1366x768   

                                       Cpu Ram Memory  \
0                     Intel Core i5 2.3GHz   8    128   
1                     Intel Core i5 1.8GHz   8    128   
2               Intel Core i5 7200U 2.5GHz   8    256   
3                     Intel Core i7 2.7GHz  16    512   
4                     Intel Core i5 3.1GHz   8    256   
...                                    ...  ..    ...   
1298            Intel Core i7 6500U 2.5GHz   4    128   
1299            Intel Core i7 6500U 2.5GHz  16    512   
1300  Intel Celeron Dual Core N3050 1.6GHz   2     64   
1301            Intel Core i7 6500U 2.5GHz   6    1TB   
1302  Intel Celeron Dual Core N3050 1.6GHz   4    500   

                               Gpu       OpSys Weight        Price  \
0     Intel Iris Plus Graphics 640       macOS   1.37   71378.6832   
1           Intel HD Graphics 6000       macOS   1.34   47895.5232   
2            Intel HD Graphics 620       No OS   1.86   30636.0000   
3               AMD Radeon Pro 455       macOS   1.83  135195.3360   
4     Intel Iris Plus Graphics 650       macOS   1.37   96095.8080   
...                            ...         ...    ...          ...   
1298         Intel HD Graphics 520  Windows 10    1.8   33992.6400   
1299         Intel HD Graphics 520  Windows 10    1.3   79866.7200   
1300             Intel HD Graphics  Windows 10    1.5   12201.1200   
1301            AMD Radeon R5 M330  Windows 10   2.19   40705.9200   
1302             Intel HD Graphics  Windows 10    2.2   19660.3200   

               Type  
0               SSD  
1     Flash Storage  
2               SSD  
3               SSD  
4               SSD  
...             ...  
1298            SSD  
1299            SSD  
1300  Flash Storage  
1301            HDD  
1302            HDD  

[1303 rows x 13 columns]

In [13]:
def split_GPU_column(df1, column_name):
    # Split the column into two new columns based on the last space
    df1[['Gpu', 'GPU_Ghz']] = df1[column_name].str.rsplit(' ', n=1, expand=True)
    return df1

In [14]:
df1 = split_GPU_column(df1, 'Gpu')
df1

Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3   
1            1.0   Apple           Ultrabook   13.3   
2            2.0      HP            Notebook   15.6   
3            3.0   Apple           Ultrabook   15.4   
4            4.0   Apple           Ultrabook   13.3   
...          ...     ...                 ...    ...   
1298      1298.0  Lenovo  2 in 1 Convertible     14   
1299      1299.0  Lenovo  2 in 1 Convertible   13.3   
1300      1300.0  Lenovo            Notebook     14   
1301      1301.0      HP            Notebook   15.6   
1302      1302.0    Asus            Notebook   15.6   

                                ScreenResolution  \
0             IPS Panel Retina Display 2560x1600   
1                                       1440x900   
2                              Full HD 1920x1080   
3             IPS Panel Retina Display 2880x1800   
4             IPS Panel Retina Display 2560x1600   
...                                          ...   
1298   IPS Panel Full HD / Touchscreen 1920x1080   
1299  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300                                    1366x768   
1301                                    1366x768   
1302                                    1366x768   

                                       Cpu Ram Memory  \
0                     Intel Core i5 2.3GHz   8    128   
1                     Intel Core i5 1.8GHz   8    128   
2               Intel Core i5 7200U 2.5GHz   8    256   
3                     Intel Core i7 2.7GHz  16    512   
4                     Intel Core i5 3.1GHz   8    256   
...                                    ...  ..    ...   
1298            Intel Core i7 6500U 2.5GHz   4    128   
1299            Intel Core i7 6500U 2.5GHz  16    512   
1300  Intel Celeron Dual Core N3050 1.6GHz   2     64   
1301            Intel Core i7 6500U 2.5GHz   6    1TB   
1302  Intel Celeron Dual Core N3050 1.6GHz   4    500   

                           Gpu       OpSys Weight        Price           Type  \
0     Intel Iris Plus Graphics       macOS   1.37   71378.6832            SSD   
1            Intel HD Graphics       macOS   1.34   47895.5232  Flash Storage   
2            Intel HD Graphics       No OS   1.86   30636.0000            SSD   
3               AMD Radeon Pro       macOS   1.83  135195.3360            SSD   
4     Intel Iris Plus Graphics       macOS   1.37   96095.8080            SSD   
...                        ...         ...    ...          ...            ...   
1298         Intel HD Graphics  Windows 10    1.8   33992.6400            SSD   
1299         Intel HD Graphics  Windows 10    1.3   79866.7200            SSD   
1300                  Intel HD  Windows 10    1.5   12201.1200  Flash Storage   
1301             AMD Radeon R5  Windows 10   2.19   40705.9200            HDD   
1302                  Intel HD  Windows 10    2.2   19660.3200            HDD   

       GPU_Ghz  
0          640  
1         6000  
2          620  
3          455  
4          650  
...        ...  
1298       520  
1299       520  
1300  Graphics  
1301      M330  
1302  Graphics  

[1303 rows x 14 columns]

In [15]:
def split_Screen_column(df1, column_name):
    # Split the column into two new columns based on the last space
    df1[['ScreenResolution', 'Resolution']] = df1[column_name].str.rsplit(' ', n=1, expand=True)
    return df1

In [16]:
df1 = split_Screen_column(df1, 'ScreenResolution')
df1

Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3   
1            1.0   Apple           Ultrabook   13.3   
2            2.0      HP            Notebook   15.6   
3            3.0   Apple           Ultrabook   15.4   
4            4.0   Apple           Ultrabook   13.3   
...          ...     ...                 ...    ...   
1298      1298.0  Lenovo  2 in 1 Convertible     14   
1299      1299.0  Lenovo  2 in 1 Convertible   13.3   
1300      1300.0  Lenovo            Notebook     14   
1301      1301.0      HP            Notebook   15.6   
1302      1302.0    Asus            Notebook   15.6   

                      ScreenResolution                                   Cpu  \
0             IPS Panel Retina Display                  Intel Core i5 2.3GHz   
1                             1440x900                  Intel Core i5 1.8GHz   
2                              Full HD            Intel Core i5 7200U 2.5GHz   
3             IPS Panel Retina Display                  Intel Core i7 2.7GHz   
4             IPS Panel Retina Display                  Intel Core i5 3.1GHz   
...                                ...                                   ...   
1298   IPS Panel Full HD / Touchscreen            Intel Core i7 6500U 2.5GHz   
1299  IPS Panel Quad HD+ / Touchscreen            Intel Core i7 6500U 2.5GHz   
1300                          1366x768  Intel Celeron Dual Core N3050 1.6GHz   
1301                          1366x768            Intel Core i7 6500U 2.5GHz   
1302                          1366x768  Intel Celeron Dual Core N3050 1.6GHz   

     Ram Memory                       Gpu       OpSys Weight        Price  \
0      8    128  Intel Iris Plus Graphics       macOS   1.37   71378.6832   
1      8    128         Intel HD Graphics       macOS   1.34   47895.5232   
2      8    256         Intel HD Graphics       No OS   1.86   30636.0000   
3     16    512            AMD Radeon Pro       macOS   1.83  135195.3360   
4      8    256  Intel Iris Plus Graphics       macOS   1.37   96095.8080   
...   ..    ...                       ...         ...    ...          ...   
1298   4    128         Intel HD Graphics  Windows 10    1.8   33992.6400   
1299  16    512         Intel HD Graphics  Windows 10    1.3   79866.7200   
1300   2     64                  Intel HD  Windows 10    1.5   12201.1200   
1301   6    1TB             AMD Radeon R5  Windows 10   2.19   40705.9200   
1302   4    500                  Intel HD  Windows 10    2.2   19660.3200   

               Type   GPU_Ghz Resolution  
0               SSD       640  2560x1600  
1     Flash Storage      6000       None  
2               SSD       620  1920x1080  
3               SSD       455  2880x1800  
4               SSD       650  2560x1600  
...             ...       ...        ...  
1298            SSD       520  1920x1080  
1299            SSD       520  3200x1800  
1300  Flash Storage  Graphics       None  
1301            HDD      M330       None  
1302            HDD  Graphics       None  

[1303 rows x 15 columns]

In [17]:
def split_Cpu_column(df1, column_name):
    # Split the column into two new columns based on the last space
    df1[['Cpu', 'Cpu_Ghz']] = df1[column_name].str.rsplit(' ', n=1, expand=True)
    return df1

In [18]:
df1 = split_Cpu_column(df1, 'Cpu')
df1

Unnamed: 0 Company            TypeName Inches  \
0            0.0   Apple           Ultrabook   13.3   
1            1.0   Apple           Ultrabook   13.3   
2            2.0      HP            Notebook   15.6   
3            3.0   Apple           Ultrabook   15.4   
4            4.0   Apple           Ultrabook   13.3   
...          ...     ...                 ...    ...   
1298      1298.0  Lenovo  2 in 1 Convertible     14   
1299      1299.0  Lenovo  2 in 1 Convertible   13.3   
1300      1300.0  Lenovo            Notebook     14   
1301      1301.0      HP            Notebook   15.6   
1302      1302.0    Asus            Notebook   15.6   

                      ScreenResolution                            Cpu Ram  \
0             IPS Panel Retina Display                  Intel Core i5   8   
1                             1440x900                  Intel Core i5   8   
2                              Full HD            Intel Core i5 7200U   8   
3             IPS Panel Retina Display                  Intel Core i7  16   
4             IPS Panel Retina Display                  Intel Core i5   8   
...                                ...                            ...  ..   
1298   IPS Panel Full HD / Touchscreen            Intel Core i7 6500U   4   
1299  IPS Panel Quad HD+ / Touchscreen            Intel Core i7 6500U  16   
1300                          1366x768  Intel Celeron Dual Core N3050   2   
1301                          1366x768            Intel Core i7 6500U   6   
1302                          1366x768  Intel Celeron Dual Core N3050   4   

     Memory                       Gpu       OpSys Weight        Price  \
0       128  Intel Iris Plus Graphics       macOS   1.37   71378.6832   
1       128         Intel HD Graphics       macOS   1.34   47895.5232   
2       256         Intel HD Graphics       No OS   1.86   30636.0000   
3       512            AMD Radeon Pro       macOS   1.83  135195.3360   
4       256  Intel Iris Plus Graphics       macOS   1.37   96095.8080   
...     ...                       ...         ...    ...          ...   
1298    128         Intel HD Graphics  Windows 10    1.8   33992.6400   
1299    512         Intel HD Graphics  Windows 10    1.3   79866.7200   
1300     64                  Intel HD  Windows 10    1.5   12201.1200   
1301    1TB             AMD Radeon R5  Windows 10   2.19   40705.9200   
1302    500                  Intel HD  Windows 10    2.2   19660.3200   

               Type   GPU_Ghz Resolution Cpu_Ghz  
0               SSD       640  2560x1600  2.3GHz  
1     Flash Storage      6000       None  1.8GHz  
2               SSD       620  1920x1080  2.5GHz  
3               SSD       455  2880x1800  2.7GHz  
4               SSD       650  2560x1600  3.1GHz  
...             ...       ...        ...     ...  
1298            SSD       520  1920x1080  2.5GHz  
1299            SSD       520  3200x1800  2.5GHz  
1300  Flash Storage  Graphics       None  1.6GHz  
1301            HDD      M330       None  2.5GHz  
1302            HDD  Graphics       None  1.6GHz  

[1303 rows x 16 columns]

In [30]:
category = df1.select_dtypes(exclude = np.number).columns
le = LabelEncoder()
classes = dict()
indices_to_print = [3, 6, 7, 10, 14, 15]
cat = df1.columns[indices_to_print]
for i in category:
    df1[i] = le.fit_transform(df1[i])
    classes[i] = le.classes_
df1

Unnamed: 0  Company  TypeName  Inches  ScreenResolution  Cpu  Ram  \
0            0.0        1         4       7                16   51    9   
1            1.0        1         4       7                 1   51    9   
2            2.0        7         3      14                 7   57    9   
3            3.0        1         4      13                16   65    2   
4            4.0        1         4       7                16   51    9   
...          ...      ...       ...     ...               ...  ...  ...   
1298      1298.0       10         0      10                13   66    6   
1299      1299.0       10         0       7                15   66    2   
1300      1300.0       10         3      10                 0   31    3   
1301      1301.0        7         3      14                 0   66    7   
1302      1302.0        2         3      14                 0   31    6   

      Memory  Gpu  OpSys  Weight        Price  Type  GPU_Ghz  Resolution  \
0          1   18      8      40   71378.6832     5       30           8   
1          1   15      8      37   47895.5232     0       26          13   
2          6   15      4      76   30636.0000     5       28           1   
3         11    5      8      73  135195.3360     5       13          10   
4          6   18      8      40   96095.8080     5       31           8   
...      ...  ...    ...     ...          ...   ...      ...         ...   
1298       1   15      5      72   33992.6400     5       18           1   
1299      11   15      5      34   79866.7200     5       18          11   
1300      12   14      5      52   12201.1200     0       48          13   
1301       4    8      5     107   40705.9200     2       56          13   
1302       9   14      5     109   19660.3200     2       48          13   

      Cpu_Ghz  
0          15  
1           9  
2          18  
3          21  
4          25  
...       ...  
1298       18  
1299       18  
1300        8  
1301       18  
1302        8  

[1303 rows x 16 columns]

In [32]:
X = df1.drop(columns = ['Price', 'Unnamed: 0']).values
X

array([[ 1,  4,  7, ..., 30,  8, 15],
       [ 1,  4,  7, ..., 26, 13,  9],
       [ 7,  3, 14, ..., 28,  1, 18],
       ...,
       [10,  3, 10, ..., 48, 13,  8],
       [ 7,  3, 14, ..., 56, 13, 18],
       [ 2,  3, 14, ..., 48, 13,  8]], dtype=int64)

In [33]:
y = df1['Price'].values
y

array([71378.6832, 47895.5232, 30636.    , ..., 12201.12  , 40705.92  ,
       19660.32  ])

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_test.shape

(391, 14)

In [35]:
reg = LinearRegression() 
reg.fit(X_train, y_train)

LinearRegression()

In [36]:
y_pred = reg.predict(X_test)

In [37]:
y_pred[:10]

array([73055.17153304, 70695.64424237,  5459.72443942, 60297.92709257,
       64116.89362691, 75776.72165083, 48440.28808042, 49108.16316159,
       83498.25007238,  5787.62222228])

In [38]:
y_test[:10]

array([89084.16, 61218.72, 26586.72, 47898.72, 44701.92, 57755.52,
       38308.32, 24455.52, 63456.48, 18594.72])

In [39]:
np.mean(np.square(y_test - y_pred))

737640761.8621016

In [40]:
np.mean(np.absolute(y_test - y_pred))

17814.235607889932

In [41]:
min(y), max(y)

(9270.72, 324954.72)

In [42]:
y_mean = np.mean(y_test)
TSS = np.sum(np.square(y_test - y_mean))
RSS = np.sum(np.square(y_test - y_pred))
1- RSS/ TSS

0.5190561998307615

In [43]:

r2_score(y_test, y_pred), mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred)


(0.5190561998307615, 737640761.8621016, 17814.235607889932)

In [47]:
df3 = df.copy()
category = df.select_dtypes(exclude = np.number).columns
classes = dict()
le = LabelEncoder()
for col in category:
    df3[col]= le.fit_transform(df3[col])
    classes[col] = le.classes_

In [48]:
X = df3.drop(columns = ['Price', 'Unnamed: 0'], ).values
X

array([[  1,   4,   7, ...,  58,   8,  39],
       [  1,   4,   7, ...,  51,   8,  36],
       [  7,   3,  14, ...,  53,   4,  75],
       ...,
       [ 10,   3,  10, ...,  40,   5,  57],
       [  7,   3,  14, ...,  21,   5, 106],
       [  2,   3,  14, ...,  40,   5, 115]])

In [49]:
y = df3['Price'].values
y

array([71378.6832, 47895.5232, 30636.    , ..., 12201.12  , 40705.92  ,
       19660.32  ])

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_test.shape

(391, 10)

In [51]:
reg = LinearRegression() 
reg.fit(X_train, y_train)

LinearRegression()

In [52]:
y_pred = reg.predict(X_test)

In [53]:
y_pred[:10]

array([67340.93238964, 63001.16102097,  5548.16706465, 76704.86454569,
       87207.57542009, 78857.95597069, 47872.57526942, 37520.29443536,
       70130.26341213, 26408.76653102])

In [54]:
y_test[:10]

array([89084.16, 61218.72, 26586.72, 47898.72, 44701.92, 57755.52,
       38308.32, 24455.52, 63456.48, 18594.72])

In [55]:
np.mean(np.square(y_test - y_pred))

906141024.9766375

In [56]:
np.mean(np.absolute(y_test - y_pred))

20641.414395595926

In [57]:
min(y), max(y)

(9270.72, 324954.72)

In [59]:
y_mean = np.mean(y_test)
TSS = np.sum(np.square(y_test - y_mean))
RSS = np.sum(np.square(y_test - y_pred))
1- RSS/ TSS

0.4091935660640942